version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "rails"
    ignore:
      - dependency-name: "rails"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"